openapi: 3.0.0
x-stoplight:
  id: h1iobyygo7ibb
info:
  title: GITAPIProject3.0Y
  version: '1.0'
  description: testyruyttg
  contact:
    name: yresrsrs
    url: 'http://localhost:3000khuyuyuy8688868'
    email: anki@gmail.com
  termsOfService: 'http://localhost:30002424i90uu'
  license:
    name: post-user66
    url: 'https://apy76i8yuiut8iyi.example.com'
servers:
  - url: 'http://localhost:3000'
    description: serverrrrrrrrrrrr
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: p3etm4z67goxm
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: 4ee1kx12fjrvl
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
              properties:
                firstName:
                  type: array
                  items:
                    x-stoplight:
                      id: 5ygwrts5reab5
                    type: array
                    items:
                      x-stoplight:
                        id: mskzfu3pe9g7y
                      enum: []
                lastName:
                  type: integer
                email:
                  type: boolean
                  default: true
                dateOfBirth:
                  type: string
                  format: date
                tcace:
                  type: string
                  x-stoplight:
                    id: mskzfu3pe9g7y
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: n1m3ikhht7jfm
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: i80atd3gvi5ox
        firstName:
          type: string
          x-stoplight:
            id: cv2lsb07jri5v
        lastName:
          type: string
          x-stoplight:
            id: erwt1hvauhc9t
        email:
          type: string
          format: email
          x-stoplight:
            id: uko6pfjqs6c8e
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: rc5oldhp3v2qr
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: f9wo3ir72fk4z
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 807edrx80vnf8
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: 61lgz9vaa7db3
  securitySchemes:
    apiKey_1:
      type: http
      scheme: bearer
    apiKey_2:
      type: http
      scheme: basic
    apiKey_3:
      name: apiKey
      type: apiKey
      in: cookie
    apiKey_4:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'localhost:3000676686868868'
          refreshUrl: 'https://api44444.example.com'
          scopes:
            scope_1: jgjguhuututyu
            scope_2: ghffydtdy
    apiKey_5:
      type: openIdConnect
      openIdConnectUrl: 'https://api.example.com'
      description: test
security:
  - apiKey_3: []
    apiKey_1: []
    apiKey_5: []
    apiKey_2: []
x-extension-1: 67688b yitt t
x-extension-2: 67688b yitt t
x-extension-3: 67688b yitt t
x-internal: true
